framework:
    profiler: { only_exceptions: false }
    messenger:
        transports:
            async: "%env(MESSENGER_TRANSPORT_DSN)%"

parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude: '../src/{DependencyInjection,Entity,Kernel.php}'
